package my_final_package;


import db.connect.dbconnects;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class panel_main extends javax.swing.JPanel {

PreparedStatement pst;
ResultSet rs;
Connection con;
   
    
    public panel_main() {
        initComponents();
        updateBookCounts();
        
        
    }
    private int countUnavailableBooks(Connection connection) {
       String query = "SELECT COUNT(*) AS unavailable_count FROM tbl_bookdata WHERE status = 'Unavailable';";
        int count = 0;

        try (PreparedStatement preparedStatement = connection.prepareStatement(query);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            if (resultSet.next()) {
                count = resultSet.getInt("unavailable_count");
                System.out.println(count);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return count;
    }

    // Method to update the counts in the UI
    public void updateBookCounts() {
        try {
            
            Connection connection = dbconnects.connectDB(); 
            int unavailableCount = countUnavailableBooks(connection);
            int availableCount = countAavailableBooks(connection);
            int dued = countDuedBooks(connection);

            
            lbl_BorrowedCount1.setText(String.valueOf(unavailableCount));
            lbl_DueCount.setText(String.valueOf(dued));
            lbl_AvailableCount.setText(String.valueOf(availableCount)); 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private int countAavailableBooks(Connection connection) {
        String query = "SELECT COUNT(*) AS available_count FROM tbl_bookdata WHERE status = 'Available'";
        int count = 0;

        try (PreparedStatement preparedStatement = connection.prepareStatement(query);
             ResultSet resultSet = preparedStatement.executeQuery()) {

            if (resultSet.next()) {
                count = resultSet.getInt("available_count");
                System.out.println(count);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return count;
    }
    
    private int countDuedBooks(Connection con) {
        String query = "SELECT COUNT(*) AS dued_books FROM tbl_borrower WHERE date < DATE('now')";

        int count = 0;
        try (PreparedStatement pst = con.prepareStatement(query);
             ResultSet rs = pst.executeQuery()) {
            
            if (rs.next()) {
                count = rs.getInt("dued_books");
                        
            }
            
        }catch(Exception e) {
            e.printStackTrace();
        }
            return count;
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_countBorrowed = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_BorrowedCount1 = new javax.swing.JLabel();
        panel_countDue = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_DueCount = new javax.swing.JLabel();
        panel_countAvailable = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_AvailableCount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 225, 207));
        setLayout(null);

        panel_header.setBackground(new java.awt.Color(77, 113, 166));
        panel_header.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Libro Link - BBS");
        panel_header.add(jLabel4);
        jLabel4.setBounds(20, 6, 250, 30);

        add(panel_header);
        panel_header.setBounds(40, 20, 600, 40);

        panel_countBorrowed.setBackground(new java.awt.Color(238, 225, 207));
        panel_countBorrowed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_countBorrowed.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(38, 53, 96));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Borrowed Books");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 160, 40);

        panel_countBorrowed.add(jPanel1);
        jPanel1.setBounds(0, 0, 160, 40);

        lbl_BorrowedCount1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_BorrowedCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_countBorrowed.add(lbl_BorrowedCount1);
        lbl_BorrowedCount1.setBounds(0, 40, 160, 120);

        add(panel_countBorrowed);
        panel_countBorrowed.setBounds(80, 90, 160, 160);

        panel_countDue.setBackground(new java.awt.Color(238, 225, 207));
        panel_countDue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_countDue.setForeground(new java.awt.Color(238, 225, 207));
        panel_countDue.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(38, 53, 96));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dued Books");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 160, 40);

        panel_countDue.add(jPanel2);
        jPanel2.setBounds(0, 0, 160, 40);

        lbl_DueCount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_DueCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_countDue.add(lbl_DueCount);
        lbl_DueCount.setBounds(0, 40, 160, 120);

        add(panel_countDue);
        panel_countDue.setBounds(460, 90, 160, 160);

        panel_countAvailable.setBackground(new java.awt.Color(238, 225, 207));
        panel_countAvailable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_countAvailable.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(38, 53, 96));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AvailableBooks");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 160, 40);

        panel_countAvailable.add(jPanel3);
        jPanel3.setBounds(0, 0, 160, 40);

        lbl_AvailableCount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_AvailableCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_countAvailable.add(lbl_AvailableCount);
        lbl_AvailableCount.setBounds(0, 40, 160, 120);

        add(panel_countAvailable);
        panel_countAvailable.setBounds(270, 90, 160, 160);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_AvailableCount;
    private javax.swing.JLabel lbl_BorrowedCount1;
    private javax.swing.JLabel lbl_DueCount;
    private javax.swing.JPanel panel_countAvailable;
    private javax.swing.JPanel panel_countBorrowed;
    private javax.swing.JPanel panel_countDue;
    private javax.swing.JPanel panel_header;
    // End of variables declaration//GEN-END:variables
}
